# Use an official Node.js runtime as the base image
FROM node:latest AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Install dependencies
RUN npm install --force

# Copy the rest of the application code to the working directory
COPY . .

# Build the Angular app
RUN ng build --prod

# Use a lightweight Node.js image for the production environment
FROM nginx:alpine

# Copy the built Angular app from the 'builder' stage to the nginx web server's root directory
COPY --from=builder /app/dist/tetherfi-app /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Command to run the nginx server
CMD ["nginx", "-g", "daemon off;"]
